class Launch_Prop:
    FILE = "LAUNCH_FILE"
    COMPUTE = "LAUNCH_COMPMODE"
    WGMODE = "LAUNCH_WGMODE"
    GAUSSIAN = "LAUNCH_GAUSSIAN"
    MULTIMODE = "LAUNCH_MULTIMODE"
    PLANEWAVE = "LAUNCH_PLANEWAVE"

class Monitor_Prop:
    FILE_POWER = "MONITOR_FILE_POWER"
    FILE_PHASE = "MONITOR_FILE_PHASE"
    WGMODE_POWER = "MONITOR_WGMODE_POWER"
    WGMODE_PHASE = "MONITOR_WGMODE_PHASE"
    GAUSS_POWER = "MONITOR_GAUSS_POWER"
    GAUSS_PHASE = "MONITOR_GAUSS_PHASE"
    LAUNCH_POWER = "MONITOR_LAUNCH_POWER"
    LAUNCH_PHASE = "MONITOR_LAUNCH_PHASE"
    WG_POWER = "MONITOR_WG_POWER"
    TOTAL_POWER = "MONITOR_TOTAL_POWER"
    FIELD_NEFF = "MONITOR_FIELD_NEFF"
    FIELD_WIDTH = "MONITOR_FIELD_WIDTH"
    FIELD_HEIGHT = "MONITOR_FIELD_HEIGHT"

class Monitor_comp:
    MAJOR = "COMPONENT_MAJOR"
    MINOR = "COMPONENT_MINOR"

class Struct_type:
    FIBRE = "STRUCT_FIBER"

class Sim_tool:
    BP = "ST_BEAMPROP"